name: OPA + Terraform Cloud

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  opa-check:
    name: Run OPA Policy Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install OPA
        run: |
          curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64
          chmod +x opa
          sudo mv opa /usr/local/bin/

      - name: Run OPA check
        run: |
          opa eval --format pretty \
          --data policy/s3.rego \
          --input main.tf \
          "data.terraform.allow"
          
  terraform-cloud-run:
    name: Trigger Terraform Cloud Run
    needs: opa-check
    runs-on: ubuntu-latest
    if: success() # only runs if OPA job succeeded
    steps:
      - name: Trigger Terraform Cloud Run
        env:
          TFC_TOKEN: ${{ secrets.TFC_TOKEN }}
          TFC_ORG: "terraform-opa-testing"
          TFC_WORKSPACE: "terraform-opa-demo"
        run: |
          curl \
            --header "Authorization: Bearer $TFC_TOKEN" \
            --header "Content-Type: application/vnd.api+json" \
            --request POST \
            --data @- \
            https://app.terraform.io/api/v2/workspaces/${TFC_WORKSPACE}/runs <<EOF
          {
            "data": {
              "attributes": {
                "message": "Triggered from GitHub Actions after OPA passed",
                "is-destroy": false
              },
              "type": "runs",
              "relationships": {
                "workspace": {
                  "data": {
                    "type": "workspaces",
                    "id": "${TFC_WORKSPACE}"
                  }
                }
              }
            }
          }
          EOF
