name: Terraform OPA CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TFC_TOKEN: ${{ secrets.TFC_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6

      - name: Terraform Init
        run: terraform init

      - name: Terraform Format
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      - name: OPA Policy Check
        run: |
          wget https://openpolicyagent.org/downloads/latest/opa_linux_amd64 -O opa
          chmod +x opa
          ./opa eval --format pretty --data policy/s3_policy.rego --input tfplan.json "data.terraform.deny"

      # Push to Terraform Cloud (triggers TFC UI run)
      - name: Trigger Terraform Cloud Apply
        run: terraform apply -auto-approve
