name: Terraform + OPA CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  terraform:
    runs-on: ubuntu-latest
    env:
      TFC_TOKEN: ${{ secrets.TFC_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.7.0

      - name: Run OPA policy check
        uses: open-policy-agent/setup-opa@v2
        with:
          version: latest

      - name: Validate Terraform files
        run: terraform fmt -check && terraform validate

      - name: Run OPA against Terraform plan
        run: |
          terraform init
          terraform plan -out=tfplan.binary
          terraform show -json tfplan.binary > tfplan.json
          opa eval --format pretty --data policy/ --input tfplan.json "data.terraform.deny"

      - name: Push to Terraform Cloud
        run: terraform apply -auto-approve
